/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteLinksByUuid200Response
 */
export interface DeleteLinksByUuid200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteLinksByUuid200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the DeleteLinksByUuid200Response interface.
 */
export function instanceOfDeleteLinksByUuid200Response(value: object): value is DeleteLinksByUuid200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function DeleteLinksByUuid200ResponseFromJSON(json: any): DeleteLinksByUuid200Response {
    return DeleteLinksByUuid200ResponseFromJSONTyped(json, false);
}

export function DeleteLinksByUuid200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteLinksByUuid200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function DeleteLinksByUuid200ResponseToJSON(json: any): DeleteLinksByUuid200Response {
    return DeleteLinksByUuid200ResponseToJSONTyped(json, false);
}

export function DeleteLinksByUuid200ResponseToJSONTyped(value?: DeleteLinksByUuid200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

