/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLinks200Response
 */
export interface GetLinks200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetLinks200Response
     */
    uuids: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof GetLinks200Response
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinks200Response
     */
    pages: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinks200Response
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinks200Response
     */
    count: number;
}

/**
 * Check if a given object implements the GetLinks200Response interface.
 */
export function instanceOfGetLinks200Response(value: object): value is GetLinks200Response {
    if (!('uuids' in value) || value['uuids'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function GetLinks200ResponseFromJSON(json: any): GetLinks200Response {
    return GetLinks200ResponseFromJSONTyped(json, false);
}

export function GetLinks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'uuids': json['uuids'],
        'page': json['page'],
        'pages': json['pages'],
        'limit': json['limit'],
        'count': json['count'],
    };
}

export function GetLinks200ResponseToJSON(json: any): GetLinks200Response {
    return GetLinks200ResponseToJSONTyped(json, false);
}

export function GetLinks200ResponseToJSONTyped(value?: GetLinks200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuids': value['uuids'],
        'page': value['page'],
        'pages': value['pages'],
        'limit': value['limit'],
        'count': value['count'],
    };
}

