/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetLinksByLinkUuidPayments200ResponsePagination } from './get-links-by-link-uuid-payments200-response-pagination';
import {
    GetLinksByLinkUuidPayments200ResponsePaginationFromJSON,
    GetLinksByLinkUuidPayments200ResponsePaginationFromJSONTyped,
    GetLinksByLinkUuidPayments200ResponsePaginationToJSON,
    GetLinksByLinkUuidPayments200ResponsePaginationToJSONTyped,
} from './get-links-by-link-uuid-payments200-response-pagination';
import type { GetLinksByLinkUuidPayments200ResponsePaymentsInner } from './get-links-by-link-uuid-payments200-response-payments-inner';
import {
    GetLinksByLinkUuidPayments200ResponsePaymentsInnerFromJSON,
    GetLinksByLinkUuidPayments200ResponsePaymentsInnerFromJSONTyped,
    GetLinksByLinkUuidPayments200ResponsePaymentsInnerToJSON,
    GetLinksByLinkUuidPayments200ResponsePaymentsInnerToJSONTyped,
} from './get-links-by-link-uuid-payments200-response-payments-inner';

/**
 * 
 * @export
 * @interface GetLinksByLinkUuidPayments200Response
 */
export interface GetLinksByLinkUuidPayments200Response {
    /**
     * 
     * @type {Array<GetLinksByLinkUuidPayments200ResponsePaymentsInner>}
     * @memberof GetLinksByLinkUuidPayments200Response
     */
    payments: Array<GetLinksByLinkUuidPayments200ResponsePaymentsInner>;
    /**
     * 
     * @type {GetLinksByLinkUuidPayments200ResponsePagination}
     * @memberof GetLinksByLinkUuidPayments200Response
     */
    pagination: GetLinksByLinkUuidPayments200ResponsePagination;
}

/**
 * Check if a given object implements the GetLinksByLinkUuidPayments200Response interface.
 */
export function instanceOfGetLinksByLinkUuidPayments200Response(value: object): value is GetLinksByLinkUuidPayments200Response {
    if (!('payments' in value) || value['payments'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidPayments200ResponseFromJSON(json: any): GetLinksByLinkUuidPayments200Response {
    return GetLinksByLinkUuidPayments200ResponseFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidPayments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidPayments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'payments': ((json['payments'] as Array<any>).map(GetLinksByLinkUuidPayments200ResponsePaymentsInnerFromJSON)),
        'pagination': GetLinksByLinkUuidPayments200ResponsePaginationFromJSON(json['pagination']),
    };
}

export function GetLinksByLinkUuidPayments200ResponseToJSON(json: any): GetLinksByLinkUuidPayments200Response {
    return GetLinksByLinkUuidPayments200ResponseToJSONTyped(json, false);
}

export function GetLinksByLinkUuidPayments200ResponseToJSONTyped(value?: GetLinksByLinkUuidPayments200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payments': ((value['payments'] as Array<any>).map(GetLinksByLinkUuidPayments200ResponsePaymentsInnerToJSON)),
        'pagination': GetLinksByLinkUuidPayments200ResponsePaginationToJSON(value['pagination']),
    };
}

