/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner } from './get-links-by-link-uuid-tolls-active200-response-toll-payment-requirements-inner';
import {
    GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerFromJSON,
    GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerFromJSONTyped,
    GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerToJSON,
    GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerToJSONTyped,
} from './get-links-by-link-uuid-tolls-active200-response-toll-payment-requirements-inner';

/**
 * 
 * @export
 * @interface GetLinksByLinkUuidTollsActive200Response
 */
export interface GetLinksByLinkUuidTollsActive200Response {
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidTollsActive200Response
     */
    uuid: string;
    /**
     * 
     * @type {Array<GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner>}
     * @memberof GetLinksByLinkUuidTollsActive200Response
     */
    tollPaymentRequirements: Array<GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner>;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidTollsActive200Response
     */
    paymentValidityPeriodSeconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidTollsActive200Response
     */
    paymentValidityQueryCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidTollsActive200Response
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidTollsActive200Response
     */
    updatedAt: string | null;
}

/**
 * Check if a given object implements the GetLinksByLinkUuidTollsActive200Response interface.
 */
export function instanceOfGetLinksByLinkUuidTollsActive200Response(value: object): value is GetLinksByLinkUuidTollsActive200Response {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('tollPaymentRequirements' in value) || value['tollPaymentRequirements'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidTollsActive200ResponseFromJSON(json: any): GetLinksByLinkUuidTollsActive200Response {
    return GetLinksByLinkUuidTollsActive200ResponseFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidTollsActive200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidTollsActive200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'tollPaymentRequirements': ((json['tollPaymentRequirements'] as Array<any>).map(GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerFromJSON)),
        'paymentValidityPeriodSeconds': json['paymentValidityPeriodSeconds'] == null ? undefined : json['paymentValidityPeriodSeconds'],
        'paymentValidityQueryCount': json['paymentValidityQueryCount'] == null ? undefined : json['paymentValidityQueryCount'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function GetLinksByLinkUuidTollsActive200ResponseToJSON(json: any): GetLinksByLinkUuidTollsActive200Response {
    return GetLinksByLinkUuidTollsActive200ResponseToJSONTyped(json, false);
}

export function GetLinksByLinkUuidTollsActive200ResponseToJSONTyped(value?: GetLinksByLinkUuidTollsActive200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'tollPaymentRequirements': ((value['tollPaymentRequirements'] as Array<any>).map(GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerToJSON)),
        'paymentValidityPeriodSeconds': value['paymentValidityPeriodSeconds'],
        'paymentValidityQueryCount': value['paymentValidityQueryCount'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

