/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAccountTransactions200ResponseTransactionsInnerPayment } from './get-account-transactions200-response-transactions-inner-payment';
import {
    GetAccountTransactions200ResponseTransactionsInnerPaymentFromJSON,
    GetAccountTransactions200ResponseTransactionsInnerPaymentFromJSONTyped,
    GetAccountTransactions200ResponseTransactionsInnerPaymentToJSON,
    GetAccountTransactions200ResponseTransactionsInnerPaymentToJSONTyped,
} from './get-account-transactions200-response-transactions-inner-payment';

/**
 * 
 * @export
 * @interface GetAccountTransactions200ResponseTransactionsInner
 */
export interface GetAccountTransactions200ResponseTransactionsInner {
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInner
     */
    type: GetAccountTransactions200ResponseTransactionsInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInner
     */
    amountDollars: string;
    /**
     * 
     * @type {GetAccountTransactions200ResponseTransactionsInnerPayment}
     * @memberof GetAccountTransactions200ResponseTransactionsInner
     */
    payment: GetAccountTransactions200ResponseTransactionsInnerPayment;
}


/**
 * @export
 */
export const GetAccountTransactions200ResponseTransactionsInnerTypeEnum = {
    Payment: 'payment',
    Topup: 'topup'
} as const;
export type GetAccountTransactions200ResponseTransactionsInnerTypeEnum = typeof GetAccountTransactions200ResponseTransactionsInnerTypeEnum[keyof typeof GetAccountTransactions200ResponseTransactionsInnerTypeEnum];


/**
 * Check if a given object implements the GetAccountTransactions200ResponseTransactionsInner interface.
 */
export function instanceOfGetAccountTransactions200ResponseTransactionsInner(value: object): value is GetAccountTransactions200ResponseTransactionsInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('amountDollars' in value) || value['amountDollars'] === undefined) return false;
    if (!('payment' in value) || value['payment'] === undefined) return false;
    return true;
}

export function GetAccountTransactions200ResponseTransactionsInnerFromJSON(json: any): GetAccountTransactions200ResponseTransactionsInner {
    return GetAccountTransactions200ResponseTransactionsInnerFromJSONTyped(json, false);
}

export function GetAccountTransactions200ResponseTransactionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountTransactions200ResponseTransactionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'amountDollars': json['amountDollars'],
        'payment': GetAccountTransactions200ResponseTransactionsInnerPaymentFromJSON(json['payment']),
    };
}

export function GetAccountTransactions200ResponseTransactionsInnerToJSON(json: any): GetAccountTransactions200ResponseTransactionsInner {
    return GetAccountTransactions200ResponseTransactionsInnerToJSONTyped(json, false);
}

export function GetAccountTransactions200ResponseTransactionsInnerToJSONTyped(value?: GetAccountTransactions200ResponseTransactionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'amountDollars': value['amountDollars'],
        'payment': GetAccountTransactions200ResponseTransactionsInnerPaymentToJSON(value['payment']),
    };
}

