/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetNetworks200ResponseInnerAssetsInner } from './get-networks200-response-inner-assets-inner';
import {
    GetNetworks200ResponseInnerAssetsInnerFromJSON,
    GetNetworks200ResponseInnerAssetsInnerFromJSONTyped,
    GetNetworks200ResponseInnerAssetsInnerToJSON,
    GetNetworks200ResponseInnerAssetsInnerToJSONTyped,
} from './get-networks200-response-inner-assets-inner';

/**
 * 
 * @export
 * @interface GetNetworks200ResponseInner
 */
export interface GetNetworks200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetNetworks200ResponseInner
     */
    name: string;
    /**
     * 
     * @type {Array<GetNetworks200ResponseInnerAssetsInner>}
     * @memberof GetNetworks200ResponseInner
     */
    assets: Array<GetNetworks200ResponseInnerAssetsInner>;
}

/**
 * Check if a given object implements the GetNetworks200ResponseInner interface.
 */
export function instanceOfGetNetworks200ResponseInner(value: object): value is GetNetworks200ResponseInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('assets' in value) || value['assets'] === undefined) return false;
    return true;
}

export function GetNetworks200ResponseInnerFromJSON(json: any): GetNetworks200ResponseInner {
    return GetNetworks200ResponseInnerFromJSONTyped(json, false);
}

export function GetNetworks200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworks200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'assets': ((json['assets'] as Array<any>).map(GetNetworks200ResponseInnerAssetsInnerFromJSON)),
    };
}

export function GetNetworks200ResponseInnerToJSON(json: any): GetNetworks200ResponseInner {
    return GetNetworks200ResponseInnerToJSONTyped(json, false);
}

export function GetNetworks200ResponseInnerToJSONTyped(value?: GetNetworks200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'assets': ((value['assets'] as Array<any>).map(GetNetworks200ResponseInnerAssetsInnerToJSON)),
    };
}

