/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAccountTransactions200ResponsePagination } from './get-account-transactions200-response-pagination';
import {
    GetAccountTransactions200ResponsePaginationFromJSON,
    GetAccountTransactions200ResponsePaginationFromJSONTyped,
    GetAccountTransactions200ResponsePaginationToJSON,
    GetAccountTransactions200ResponsePaginationToJSONTyped,
} from './get-account-transactions200-response-pagination';
import type { GetAccountTransactions200ResponseTransactionsInner } from './get-account-transactions200-response-transactions-inner';
import {
    GetAccountTransactions200ResponseTransactionsInnerFromJSON,
    GetAccountTransactions200ResponseTransactionsInnerFromJSONTyped,
    GetAccountTransactions200ResponseTransactionsInnerToJSON,
    GetAccountTransactions200ResponseTransactionsInnerToJSONTyped,
} from './get-account-transactions200-response-transactions-inner';

/**
 * 
 * @export
 * @interface GetAccountTransactions200Response
 */
export interface GetAccountTransactions200Response {
    /**
     * 
     * @type {Array<GetAccountTransactions200ResponseTransactionsInner>}
     * @memberof GetAccountTransactions200Response
     */
    transactions: Array<GetAccountTransactions200ResponseTransactionsInner>;
    /**
     * 
     * @type {GetAccountTransactions200ResponsePagination}
     * @memberof GetAccountTransactions200Response
     */
    pagination: GetAccountTransactions200ResponsePagination;
}

/**
 * Check if a given object implements the GetAccountTransactions200Response interface.
 */
export function instanceOfGetAccountTransactions200Response(value: object): value is GetAccountTransactions200Response {
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function GetAccountTransactions200ResponseFromJSON(json: any): GetAccountTransactions200Response {
    return GetAccountTransactions200ResponseFromJSONTyped(json, false);
}

export function GetAccountTransactions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountTransactions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'transactions': ((json['transactions'] as Array<any>).map(GetAccountTransactions200ResponseTransactionsInnerFromJSON)),
        'pagination': GetAccountTransactions200ResponsePaginationFromJSON(json['pagination']),
    };
}

export function GetAccountTransactions200ResponseToJSON(json: any): GetAccountTransactions200Response {
    return GetAccountTransactions200ResponseToJSONTyped(json, false);
}

export function GetAccountTransactions200ResponseToJSONTyped(value?: GetAccountTransactions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactions': ((value['transactions'] as Array<any>).map(GetAccountTransactions200ResponseTransactionsInnerToJSON)),
        'pagination': GetAccountTransactions200ResponsePaginationToJSON(value['pagination']),
    };
}

