/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner
 */
export interface GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner {
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner
     */
    assetNetwork: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner
     */
    assetAddress: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner
     */
    destinationAddress: string;
}

/**
 * Check if a given object implements the GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner interface.
 */
export function instanceOfGetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner(value: object): value is GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner {
    if (!('assetNetwork' in value) || value['assetNetwork'] === undefined) return false;
    if (!('assetAddress' in value) || value['assetAddress'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('destinationAddress' in value) || value['destinationAddress'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerFromJSON(json: any): GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner {
    return GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'assetNetwork': json['assetNetwork'],
        'assetAddress': json['assetAddress'],
        'amount': json['amount'],
        'destinationAddress': json['destinationAddress'],
    };
}

export function GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerToJSON(json: any): GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner {
    return GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerToJSONTyped(json, false);
}

export function GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerToJSONTyped(value?: GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assetNetwork': value['assetNetwork'],
        'assetAddress': value['assetAddress'],
        'amount': value['amount'],
        'destinationAddress': value['destinationAddress'],
    };
}

