/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetLinksByLinkUuidStats200ResponseTopUserAgentsInner } from './get-links-by-link-uuid-stats200-response-top-user-agents-inner';
import {
    GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerFromJSON,
    GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerFromJSONTyped,
    GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerToJSON,
    GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerToJSONTyped,
} from './get-links-by-link-uuid-stats200-response-top-user-agents-inner';

/**
 * 
 * @export
 * @interface GetLinksByLinkUuidStats200Response
 */
export interface GetLinksByLinkUuidStats200Response {
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    linkUuid: string;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    totalQueries: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    successfulQueries: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    failedQueries: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    totalPayloadBytes: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    totalRevenueDollars: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    totalTransactionFeesDollars: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    averageResponseTime: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    uniqueVisitors: number;
    /**
     * 
     * @type {Date}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    lastAccessed: Date;
    /**
     * 
     * @type {Array<GetLinksByLinkUuidStats200ResponseTopUserAgentsInner>}
     * @memberof GetLinksByLinkUuidStats200Response
     */
    topUserAgents: Array<GetLinksByLinkUuidStats200ResponseTopUserAgentsInner>;
}

/**
 * Check if a given object implements the GetLinksByLinkUuidStats200Response interface.
 */
export function instanceOfGetLinksByLinkUuidStats200Response(value: object): value is GetLinksByLinkUuidStats200Response {
    if (!('linkUuid' in value) || value['linkUuid'] === undefined) return false;
    if (!('totalQueries' in value) || value['totalQueries'] === undefined) return false;
    if (!('successfulQueries' in value) || value['successfulQueries'] === undefined) return false;
    if (!('failedQueries' in value) || value['failedQueries'] === undefined) return false;
    if (!('totalPayloadBytes' in value) || value['totalPayloadBytes'] === undefined) return false;
    if (!('totalRevenueDollars' in value) || value['totalRevenueDollars'] === undefined) return false;
    if (!('totalTransactionFeesDollars' in value) || value['totalTransactionFeesDollars'] === undefined) return false;
    if (!('averageResponseTime' in value) || value['averageResponseTime'] === undefined) return false;
    if (!('uniqueVisitors' in value) || value['uniqueVisitors'] === undefined) return false;
    if (!('lastAccessed' in value) || value['lastAccessed'] === undefined) return false;
    if (!('topUserAgents' in value) || value['topUserAgents'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidStats200ResponseFromJSON(json: any): GetLinksByLinkUuidStats200Response {
    return GetLinksByLinkUuidStats200ResponseFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidStats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidStats200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'linkUuid': json['linkUuid'],
        'totalQueries': json['totalQueries'],
        'successfulQueries': json['successfulQueries'],
        'failedQueries': json['failedQueries'],
        'totalPayloadBytes': json['totalPayloadBytes'],
        'totalRevenueDollars': json['totalRevenueDollars'],
        'totalTransactionFeesDollars': json['totalTransactionFeesDollars'],
        'averageResponseTime': json['averageResponseTime'],
        'uniqueVisitors': json['uniqueVisitors'],
        'lastAccessed': (new Date(json['lastAccessed'])),
        'topUserAgents': ((json['topUserAgents'] as Array<any>).map(GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerFromJSON)),
    };
}

export function GetLinksByLinkUuidStats200ResponseToJSON(json: any): GetLinksByLinkUuidStats200Response {
    return GetLinksByLinkUuidStats200ResponseToJSONTyped(json, false);
}

export function GetLinksByLinkUuidStats200ResponseToJSONTyped(value?: GetLinksByLinkUuidStats200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'linkUuid': value['linkUuid'],
        'totalQueries': value['totalQueries'],
        'successfulQueries': value['successfulQueries'],
        'failedQueries': value['failedQueries'],
        'totalPayloadBytes': value['totalPayloadBytes'],
        'totalRevenueDollars': value['totalRevenueDollars'],
        'totalTransactionFeesDollars': value['totalTransactionFeesDollars'],
        'averageResponseTime': value['averageResponseTime'],
        'uniqueVisitors': value['uniqueVisitors'],
        'lastAccessed': ((value['lastAccessed']).toISOString()),
        'topUserAgents': ((value['topUserAgents'] as Array<any>).map(GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerToJSON)),
    };
}

