/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccountToken200Response
 */
export interface GetAccountToken200Response {
    /**
     * 
     * @type {string}
     * @memberof GetAccountToken200Response
     */
    token: string;
}

/**
 * Check if a given object implements the GetAccountToken200Response interface.
 */
export function instanceOfGetAccountToken200Response(value: object): value is GetAccountToken200Response {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function GetAccountToken200ResponseFromJSON(json: any): GetAccountToken200Response {
    return GetAccountToken200ResponseFromJSONTyped(json, false);
}

export function GetAccountToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function GetAccountToken200ResponseToJSON(json: any): GetAccountToken200Response {
    return GetAccountToken200ResponseToJSONTyped(json, false);
}

export function GetAccountToken200ResponseToJSONTyped(value?: GetAccountToken200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

