/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNetworks200ResponseInnerAssetsInner
 */
export interface GetNetworks200ResponseInnerAssetsInner {
    /**
     * 
     * @type {string}
     * @memberof GetNetworks200ResponseInnerAssetsInner
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof GetNetworks200ResponseInnerAssetsInner
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof GetNetworks200ResponseInnerAssetsInner
     */
    type: GetNetworks200ResponseInnerAssetsInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetNetworks200ResponseInnerAssetsInner
     */
    _interface: GetNetworks200ResponseInnerAssetsInnerInterfaceEnum;
    /**
     * 
     * @type {string}
     * @memberof GetNetworks200ResponseInnerAssetsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetNetworks200ResponseInnerAssetsInner
     */
    symbol: string;
    /**
     * 
     * @type {number}
     * @memberof GetNetworks200ResponseInnerAssetsInner
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof GetNetworks200ResponseInnerAssetsInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof GetNetworks200ResponseInnerAssetsInner
     */
    updatedAt: string | null;
}


/**
 * @export
 */
export const GetNetworks200ResponseInnerAssetsInnerTypeEnum = {
    Native: 'native',
    Erc20: 'erc20',
    Erc721: 'erc721'
} as const;
export type GetNetworks200ResponseInnerAssetsInnerTypeEnum = typeof GetNetworks200ResponseInnerAssetsInnerTypeEnum[keyof typeof GetNetworks200ResponseInnerAssetsInnerTypeEnum];

/**
 * @export
 */
export const GetNetworks200ResponseInnerAssetsInnerInterfaceEnum = {
    Erc2612: 'erc2612',
    Erc3009: 'erc3009',
    Erc7702: 'erc7702'
} as const;
export type GetNetworks200ResponseInnerAssetsInnerInterfaceEnum = typeof GetNetworks200ResponseInnerAssetsInnerInterfaceEnum[keyof typeof GetNetworks200ResponseInnerAssetsInnerInterfaceEnum];


/**
 * Check if a given object implements the GetNetworks200ResponseInnerAssetsInner interface.
 */
export function instanceOfGetNetworks200ResponseInnerAssetsInner(value: object): value is GetNetworks200ResponseInnerAssetsInner {
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('_interface' in value) || value['_interface'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GetNetworks200ResponseInnerAssetsInnerFromJSON(json: any): GetNetworks200ResponseInnerAssetsInner {
    return GetNetworks200ResponseInnerAssetsInnerFromJSONTyped(json, false);
}

export function GetNetworks200ResponseInnerAssetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworks200ResponseInnerAssetsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'network': json['network'],
        'address': json['address'],
        'type': json['type'],
        '_interface': json['interface'],
        'name': json['name'],
        'symbol': json['symbol'],
        'decimals': json['decimals'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function GetNetworks200ResponseInnerAssetsInnerToJSON(json: any): GetNetworks200ResponseInnerAssetsInner {
    return GetNetworks200ResponseInnerAssetsInnerToJSONTyped(json, false);
}

export function GetNetworks200ResponseInnerAssetsInnerToJSONTyped(value?: GetNetworks200ResponseInnerAssetsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': value['network'],
        'address': value['address'],
        'type': value['type'],
        'interface': value['_interface'],
        'name': value['name'],
        'symbol': value['symbol'],
        'decimals': value['decimals'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

