/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccountBalance200Response
 */
export interface GetAccountBalance200Response {
    /**
     * 
     * @type {string}
     * @memberof GetAccountBalance200Response
     */
    balanceDollars: string;
}

/**
 * Check if a given object implements the GetAccountBalance200Response interface.
 */
export function instanceOfGetAccountBalance200Response(value: object): value is GetAccountBalance200Response {
    if (!('balanceDollars' in value) || value['balanceDollars'] === undefined) return false;
    return true;
}

export function GetAccountBalance200ResponseFromJSON(json: any): GetAccountBalance200Response {
    return GetAccountBalance200ResponseFromJSONTyped(json, false);
}

export function GetAccountBalance200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountBalance200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'balanceDollars': json['balanceDollars'],
    };
}

export function GetAccountBalance200ResponseToJSON(json: any): GetAccountBalance200Response {
    return GetAccountBalance200ResponseToJSONTyped(json, false);
}

export function GetAccountBalance200ResponseToJSONTyped(value?: GetAccountBalance200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balanceDollars': value['balanceDollars'],
    };
}

