/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLinksByLinkUuidPayments200ResponsePagination
 */
export interface GetLinksByLinkUuidPayments200ResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidPayments200ResponsePagination
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidPayments200ResponsePagination
     */
    pages: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidPayments200ResponsePagination
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidPayments200ResponsePagination
     */
    count: number;
}

/**
 * Check if a given object implements the GetLinksByLinkUuidPayments200ResponsePagination interface.
 */
export function instanceOfGetLinksByLinkUuidPayments200ResponsePagination(value: object): value is GetLinksByLinkUuidPayments200ResponsePagination {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidPayments200ResponsePaginationFromJSON(json: any): GetLinksByLinkUuidPayments200ResponsePagination {
    return GetLinksByLinkUuidPayments200ResponsePaginationFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidPayments200ResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidPayments200ResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pages': json['pages'],
        'limit': json['limit'],
        'count': json['count'],
    };
}

export function GetLinksByLinkUuidPayments200ResponsePaginationToJSON(json: any): GetLinksByLinkUuidPayments200ResponsePagination {
    return GetLinksByLinkUuidPayments200ResponsePaginationToJSONTyped(json, false);
}

export function GetLinksByLinkUuidPayments200ResponsePaginationToJSONTyped(value?: GetLinksByLinkUuidPayments200ResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pages': value['pages'],
        'limit': value['limit'],
        'count': value['count'],
    };
}

