/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLinksByLinkUuidStats200ResponseTopUserAgentsInner
 */
export interface GetLinksByLinkUuidStats200ResponseTopUserAgentsInner {
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidStats200ResponseTopUserAgentsInner
     */
    userAgent: string;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidStats200ResponseTopUserAgentsInner
     */
    count: number;
}

/**
 * Check if a given object implements the GetLinksByLinkUuidStats200ResponseTopUserAgentsInner interface.
 */
export function instanceOfGetLinksByLinkUuidStats200ResponseTopUserAgentsInner(value: object): value is GetLinksByLinkUuidStats200ResponseTopUserAgentsInner {
    if (!('userAgent' in value) || value['userAgent'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerFromJSON(json: any): GetLinksByLinkUuidStats200ResponseTopUserAgentsInner {
    return GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidStats200ResponseTopUserAgentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userAgent': json['userAgent'],
        'count': json['count'],
    };
}

export function GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerToJSON(json: any): GetLinksByLinkUuidStats200ResponseTopUserAgentsInner {
    return GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerToJSONTyped(json, false);
}

export function GetLinksByLinkUuidStats200ResponseTopUserAgentsInnerToJSONTyped(value?: GetLinksByLinkUuidStats200ResponseTopUserAgentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userAgent': value['userAgent'],
        'count': value['count'],
    };
}

