/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
 */
export interface GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner {
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
     */
    actionUuid: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
     */
    actionType: string;
    /**
     * 
     * @type {any}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
     */
    actionData?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
     */
    requestUuid: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
     */
    status: GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
     */
    log: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner
     */
    updatedAt: string | null;
}


/**
 * @export
 */
export const GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerStatusEnum = {
    Pending: 'pending',
    Success: 'success',
    Failure: 'failure'
} as const;
export type GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerStatusEnum = typeof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerStatusEnum[keyof typeof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerStatusEnum];


/**
 * Check if a given object implements the GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner interface.
 */
export function instanceOfGetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner(value: object): value is GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('actionUuid' in value) || value['actionUuid'] === undefined) return false;
    if (!('actionType' in value) || value['actionType'] === undefined) return false;
    if (!('requestUuid' in value) || value['requestUuid'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('log' in value) || value['log'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerFromJSON(json: any): GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner {
    return GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'actionUuid': json['actionUuid'],
        'actionType': json['actionType'],
        'actionData': json['actionData'] == null ? undefined : json['actionData'],
        'requestUuid': json['requestUuid'],
        'status': json['status'],
        'log': json['log'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerToJSON(json: any): GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner {
    return GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerToJSONTyped(json, false);
}

export function GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerToJSONTyped(value?: GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'actionUuid': value['actionUuid'],
        'actionType': value['actionType'],
        'actionData': value['actionData'],
        'requestUuid': value['requestUuid'],
        'status': value['status'],
        'log': value['log'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

