/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccountTransactions200ResponsePagination
 */
export interface GetAccountTransactions200ResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof GetAccountTransactions200ResponsePagination
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof GetAccountTransactions200ResponsePagination
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof GetAccountTransactions200ResponsePagination
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof GetAccountTransactions200ResponsePagination
     */
    pages: number;
}

/**
 * Check if a given object implements the GetAccountTransactions200ResponsePagination interface.
 */
export function instanceOfGetAccountTransactions200ResponsePagination(value: object): value is GetAccountTransactions200ResponsePagination {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('pages' in value) || value['pages'] === undefined) return false;
    return true;
}

export function GetAccountTransactions200ResponsePaginationFromJSON(json: any): GetAccountTransactions200ResponsePagination {
    return GetAccountTransactions200ResponsePaginationFromJSONTyped(json, false);
}

export function GetAccountTransactions200ResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountTransactions200ResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'limit': json['limit'],
        'total': json['total'],
        'pages': json['pages'],
    };
}

export function GetAccountTransactions200ResponsePaginationToJSON(json: any): GetAccountTransactions200ResponsePagination {
    return GetAccountTransactions200ResponsePaginationToJSONTyped(json, false);
}

export function GetAccountTransactions200ResponsePaginationToJSONTyped(value?: GetAccountTransactions200ResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'pages': value['pages'],
    };
}

