/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccountStats200Response
 */
export interface GetAccountStats200Response {
    /**
     * 
     * @type {number}
     * @memberof GetAccountStats200Response
     */
    totalFeesPaidDollars: number;
    /**
     * 
     * @type {number}
     * @memberof GetAccountStats200Response
     */
    totalRevenueDollars: number;
}

/**
 * Check if a given object implements the GetAccountStats200Response interface.
 */
export function instanceOfGetAccountStats200Response(value: object): value is GetAccountStats200Response {
    if (!('totalFeesPaidDollars' in value) || value['totalFeesPaidDollars'] === undefined) return false;
    if (!('totalRevenueDollars' in value) || value['totalRevenueDollars'] === undefined) return false;
    return true;
}

export function GetAccountStats200ResponseFromJSON(json: any): GetAccountStats200Response {
    return GetAccountStats200ResponseFromJSONTyped(json, false);
}

export function GetAccountStats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountStats200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totalFeesPaidDollars': json['totalFeesPaidDollars'],
        'totalRevenueDollars': json['totalRevenueDollars'],
    };
}

export function GetAccountStats200ResponseToJSON(json: any): GetAccountStats200Response {
    return GetAccountStats200ResponseToJSONTyped(json, false);
}

export function GetAccountStats200ResponseToJSONTyped(value?: GetAccountStats200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalFeesPaidDollars': value['totalFeesPaidDollars'],
        'totalRevenueDollars': value['totalRevenueDollars'],
    };
}

