/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner } from './get-links-by-link-uuid-payments-by-payment-uuid-action-logs200-response-action-logs-inner';
import {
    GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerFromJSON,
    GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerFromJSONTyped,
    GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerToJSON,
    GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerToJSONTyped,
} from './get-links-by-link-uuid-payments-by-payment-uuid-action-logs200-response-action-logs-inner';

/**
 * 
 * @export
 * @interface GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response
 */
export interface GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response {
    /**
     * 
     * @type {Array<GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner>}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response
     */
    actionLogs: Array<GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInner>;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response
     */
    count: number;
}

/**
 * Check if a given object implements the GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response interface.
 */
export function instanceOfGetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response(value: object): value is GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response {
    if (!('actionLogs' in value) || value['actionLogs'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseFromJSON(json: any): GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response {
    return GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'actionLogs': ((json['actionLogs'] as Array<any>).map(GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerFromJSON)),
        'count': json['count'],
    };
}

export function GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseToJSON(json: any): GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response {
    return GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseToJSONTyped(json, false);
}

export function GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseToJSONTyped(value?: GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actionLogs': ((value['actionLogs'] as Array<any>).map(GetLinksByLinkUuidPaymentsByPaymentUuidActionLogs200ResponseActionLogsInnerToJSON)),
        'count': value['count'],
    };
}

