/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLinksByLinkUuidPayments200ResponsePaymentsInner
 */
export interface GetLinksByLinkUuidPayments200ResponsePaymentsInner {
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    requestUuid: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    linkUuid: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    tollUuid: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    error: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    facilitator: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    transactionHash: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    transactionFee: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    transactionFeeDollars: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    payerAddress: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    amount: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    amountDollars: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    assetAddress: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    destinationAddress: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    settlementDetails: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    verificationDetails: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidPayments200ResponsePaymentsInner
     */
    updatedAt: string | null;
}

/**
 * Check if a given object implements the GetLinksByLinkUuidPayments200ResponsePaymentsInner interface.
 */
export function instanceOfGetLinksByLinkUuidPayments200ResponsePaymentsInner(value: object): value is GetLinksByLinkUuidPayments200ResponsePaymentsInner {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('requestUuid' in value) || value['requestUuid'] === undefined) return false;
    if (!('linkUuid' in value) || value['linkUuid'] === undefined) return false;
    if (!('tollUuid' in value) || value['tollUuid'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('facilitator' in value) || value['facilitator'] === undefined) return false;
    if (!('transactionHash' in value) || value['transactionHash'] === undefined) return false;
    if (!('transactionFee' in value) || value['transactionFee'] === undefined) return false;
    if (!('transactionFeeDollars' in value) || value['transactionFeeDollars'] === undefined) return false;
    if (!('payerAddress' in value) || value['payerAddress'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('amountDollars' in value) || value['amountDollars'] === undefined) return false;
    if (!('assetAddress' in value) || value['assetAddress'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('destinationAddress' in value) || value['destinationAddress'] === undefined) return false;
    if (!('settlementDetails' in value) || value['settlementDetails'] === undefined) return false;
    if (!('verificationDetails' in value) || value['verificationDetails'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidPayments200ResponsePaymentsInnerFromJSON(json: any): GetLinksByLinkUuidPayments200ResponsePaymentsInner {
    return GetLinksByLinkUuidPayments200ResponsePaymentsInnerFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidPayments200ResponsePaymentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidPayments200ResponsePaymentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'requestUuid': json['requestUuid'],
        'linkUuid': json['linkUuid'],
        'tollUuid': json['tollUuid'],
        'status': json['status'],
        'error': json['error'],
        'facilitator': json['facilitator'],
        'transactionHash': json['transactionHash'],
        'transactionFee': json['transactionFee'],
        'transactionFeeDollars': json['transactionFeeDollars'],
        'payerAddress': json['payerAddress'],
        'amount': json['amount'],
        'amountDollars': json['amountDollars'],
        'assetAddress': json['assetAddress'],
        'network': json['network'],
        'destinationAddress': json['destinationAddress'],
        'settlementDetails': json['settlementDetails'],
        'verificationDetails': json['verificationDetails'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function GetLinksByLinkUuidPayments200ResponsePaymentsInnerToJSON(json: any): GetLinksByLinkUuidPayments200ResponsePaymentsInner {
    return GetLinksByLinkUuidPayments200ResponsePaymentsInnerToJSONTyped(json, false);
}

export function GetLinksByLinkUuidPayments200ResponsePaymentsInnerToJSONTyped(value?: GetLinksByLinkUuidPayments200ResponsePaymentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'requestUuid': value['requestUuid'],
        'linkUuid': value['linkUuid'],
        'tollUuid': value['tollUuid'],
        'status': value['status'],
        'error': value['error'],
        'facilitator': value['facilitator'],
        'transactionHash': value['transactionHash'],
        'transactionFee': value['transactionFee'],
        'transactionFeeDollars': value['transactionFeeDollars'],
        'payerAddress': value['payerAddress'],
        'amount': value['amount'],
        'amountDollars': value['amountDollars'],
        'assetAddress': value['assetAddress'],
        'network': value['network'],
        'destinationAddress': value['destinationAddress'],
        'settlementDetails': value['settlementDetails'],
        'verificationDetails': value['verificationDetails'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

