/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLinksByLinkUuidResourcesActive200Response
 */
export interface GetLinksByLinkUuidResourcesActive200Response {
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidResourcesActive200Response
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidResourcesActive200Response
     */
    type: GetLinksByLinkUuidResourcesActive200ResponseTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof GetLinksByLinkUuidResourcesActive200Response
     */
    data?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidResourcesActive200Response
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof GetLinksByLinkUuidResourcesActive200Response
     */
    updatedAt: string | null;
}


/**
 * @export
 */
export const GetLinksByLinkUuidResourcesActive200ResponseTypeEnum = {
    Proxy: 'proxy',
    Link: 'link',
    Redirect: 'redirect',
    Tunnel: 'tunnel',
    Html: 'html'
} as const;
export type GetLinksByLinkUuidResourcesActive200ResponseTypeEnum = typeof GetLinksByLinkUuidResourcesActive200ResponseTypeEnum[keyof typeof GetLinksByLinkUuidResourcesActive200ResponseTypeEnum];


/**
 * Check if a given object implements the GetLinksByLinkUuidResourcesActive200Response interface.
 */
export function instanceOfGetLinksByLinkUuidResourcesActive200Response(value: object): value is GetLinksByLinkUuidResourcesActive200Response {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GetLinksByLinkUuidResourcesActive200ResponseFromJSON(json: any): GetLinksByLinkUuidResourcesActive200Response {
    return GetLinksByLinkUuidResourcesActive200ResponseFromJSONTyped(json, false);
}

export function GetLinksByLinkUuidResourcesActive200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksByLinkUuidResourcesActive200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'type': json['type'],
        'data': json['data'] == null ? undefined : json['data'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function GetLinksByLinkUuidResourcesActive200ResponseToJSON(json: any): GetLinksByLinkUuidResourcesActive200Response {
    return GetLinksByLinkUuidResourcesActive200ResponseToJSONTyped(json, false);
}

export function GetLinksByLinkUuidResourcesActive200ResponseToJSONTyped(value?: GetLinksByLinkUuidResourcesActive200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'type': value['type'],
        'data': value['data'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

