/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccountTransactions200ResponseTransactionsInnerPayment
 */
export interface GetAccountTransactions200ResponseTransactionsInnerPayment {
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    amountDollars: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    assetNetwork: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    assetAddress: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    transactionHash: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    transactionFee: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    transactionFeeDollars: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    transactionDate: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransactions200ResponseTransactionsInnerPayment
     */
    linkUuid: string;
}

/**
 * Check if a given object implements the GetAccountTransactions200ResponseTransactionsInnerPayment interface.
 */
export function instanceOfGetAccountTransactions200ResponseTransactionsInnerPayment(value: object): value is GetAccountTransactions200ResponseTransactionsInnerPayment {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('amountDollars' in value) || value['amountDollars'] === undefined) return false;
    if (!('assetNetwork' in value) || value['assetNetwork'] === undefined) return false;
    if (!('assetAddress' in value) || value['assetAddress'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('transactionHash' in value) || value['transactionHash'] === undefined) return false;
    if (!('transactionFee' in value) || value['transactionFee'] === undefined) return false;
    if (!('transactionFeeDollars' in value) || value['transactionFeeDollars'] === undefined) return false;
    if (!('transactionDate' in value) || value['transactionDate'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('linkUuid' in value) || value['linkUuid'] === undefined) return false;
    return true;
}

export function GetAccountTransactions200ResponseTransactionsInnerPaymentFromJSON(json: any): GetAccountTransactions200ResponseTransactionsInnerPayment {
    return GetAccountTransactions200ResponseTransactionsInnerPaymentFromJSONTyped(json, false);
}

export function GetAccountTransactions200ResponseTransactionsInnerPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountTransactions200ResponseTransactionsInnerPayment {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'amount': json['amount'],
        'amountDollars': json['amountDollars'],
        'assetNetwork': json['assetNetwork'],
        'assetAddress': json['assetAddress'],
        'status': json['status'],
        'transactionHash': json['transactionHash'],
        'transactionFee': json['transactionFee'],
        'transactionFeeDollars': json['transactionFeeDollars'],
        'transactionDate': json['transactionDate'],
        'createdAt': json['createdAt'],
        'linkUuid': json['linkUuid'],
    };
}

export function GetAccountTransactions200ResponseTransactionsInnerPaymentToJSON(json: any): GetAccountTransactions200ResponseTransactionsInnerPayment {
    return GetAccountTransactions200ResponseTransactionsInnerPaymentToJSONTyped(json, false);
}

export function GetAccountTransactions200ResponseTransactionsInnerPaymentToJSONTyped(value?: GetAccountTransactions200ResponseTransactionsInnerPayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'amount': value['amount'],
        'amountDollars': value['amountDollars'],
        'assetNetwork': value['assetNetwork'],
        'assetAddress': value['assetAddress'],
        'status': value['status'],
        'transactionHash': value['transactionHash'],
        'transactionFee': value['transactionFee'],
        'transactionFeeDollars': value['transactionFeeDollars'],
        'transactionDate': value['transactionDate'],
        'createdAt': value['createdAt'],
        'linkUuid': value['linkUuid'],
    };
}

