/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostLinksByLinkUuidActions201Response
 */
export interface PostLinksByLinkUuidActions201Response {
    /**
     * 
     * @type {string}
     * @memberof PostLinksByLinkUuidActions201Response
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof PostLinksByLinkUuidActions201Response
     */
    linkUuid: string;
    /**
     * 
     * @type {string}
     * @memberof PostLinksByLinkUuidActions201Response
     */
    type: PostLinksByLinkUuidActions201ResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PostLinksByLinkUuidActions201Response
     */
    trigger: PostLinksByLinkUuidActions201ResponseTriggerEnum;
    /**
     * 
     * @type {any}
     * @memberof PostLinksByLinkUuidActions201Response
     */
    data?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PostLinksByLinkUuidActions201Response
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof PostLinksByLinkUuidActions201Response
     */
    updatedAt: string | null;
}


/**
 * @export
 */
export const PostLinksByLinkUuidActions201ResponseTypeEnum = {
    Callback: 'callback',
    Notification: 'notification',
    Email: 'email',
    Sms: 'sms'
} as const;
export type PostLinksByLinkUuidActions201ResponseTypeEnum = typeof PostLinksByLinkUuidActions201ResponseTypeEnum[keyof typeof PostLinksByLinkUuidActions201ResponseTypeEnum];

/**
 * @export
 */
export const PostLinksByLinkUuidActions201ResponseTriggerEnum = {
    PaymentSuccess: 'payment_success'
} as const;
export type PostLinksByLinkUuidActions201ResponseTriggerEnum = typeof PostLinksByLinkUuidActions201ResponseTriggerEnum[keyof typeof PostLinksByLinkUuidActions201ResponseTriggerEnum];


/**
 * Check if a given object implements the PostLinksByLinkUuidActions201Response interface.
 */
export function instanceOfPostLinksByLinkUuidActions201Response(value: object): value is PostLinksByLinkUuidActions201Response {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('linkUuid' in value) || value['linkUuid'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('trigger' in value) || value['trigger'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PostLinksByLinkUuidActions201ResponseFromJSON(json: any): PostLinksByLinkUuidActions201Response {
    return PostLinksByLinkUuidActions201ResponseFromJSONTyped(json, false);
}

export function PostLinksByLinkUuidActions201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLinksByLinkUuidActions201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'linkUuid': json['linkUuid'],
        'type': json['type'],
        'trigger': json['trigger'],
        'data': json['data'] == null ? undefined : json['data'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function PostLinksByLinkUuidActions201ResponseToJSON(json: any): PostLinksByLinkUuidActions201Response {
    return PostLinksByLinkUuidActions201ResponseToJSONTyped(json, false);
}

export function PostLinksByLinkUuidActions201ResponseToJSONTyped(value?: PostLinksByLinkUuidActions201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'linkUuid': value['linkUuid'],
        'type': value['type'],
        'trigger': value['trigger'],
        'data': value['data'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

