/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetLinksByLinkUuidTollsActive200Response } from './get-links-by-link-uuid-tolls-active200-response';
import {
    GetLinksByLinkUuidTollsActive200ResponseFromJSON,
    GetLinksByLinkUuidTollsActive200ResponseFromJSONTyped,
    GetLinksByLinkUuidTollsActive200ResponseToJSON,
    GetLinksByLinkUuidTollsActive200ResponseToJSONTyped,
} from './get-links-by-link-uuid-tolls-active200-response';
import type { PostLinksByLinkUuidActions201Response } from './post-links-by-link-uuid-actions201-response';
import {
    PostLinksByLinkUuidActions201ResponseFromJSON,
    PostLinksByLinkUuidActions201ResponseFromJSONTyped,
    PostLinksByLinkUuidActions201ResponseToJSON,
    PostLinksByLinkUuidActions201ResponseToJSONTyped,
} from './post-links-by-link-uuid-actions201-response';
import type { GetLinksByLinkUuidResourcesActive200Response } from './get-links-by-link-uuid-resources-active200-response';
import {
    GetLinksByLinkUuidResourcesActive200ResponseFromJSON,
    GetLinksByLinkUuidResourcesActive200ResponseFromJSONTyped,
    GetLinksByLinkUuidResourcesActive200ResponseToJSON,
    GetLinksByLinkUuidResourcesActive200ResponseToJSONTyped,
} from './get-links-by-link-uuid-resources-active200-response';

/**
 * 
 * @export
 * @interface PostLinks201Response
 */
export interface PostLinks201Response {
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    ownerId: string;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    alias: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    status: PostLinks201ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    type: PostLinks201ResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    expirationTime: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PostLinks201Response
     */
    deleted: boolean;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof PostLinks201Response
     */
    updatedAt: string | null;
    /**
     * 
     * @type {GetLinksByLinkUuidTollsActive200Response}
     * @memberof PostLinks201Response
     */
    toll: GetLinksByLinkUuidTollsActive200Response;
    /**
     * 
     * @type {GetLinksByLinkUuidResourcesActive200Response}
     * @memberof PostLinks201Response
     */
    resource: GetLinksByLinkUuidResourcesActive200Response;
    /**
     * 
     * @type {Array<PostLinksByLinkUuidActions201Response>}
     * @memberof PostLinks201Response
     */
    actions: Array<PostLinksByLinkUuidActions201Response>;
}


/**
 * @export
 */
export const PostLinks201ResponseStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Used: 'used',
    Expired: 'expired'
} as const;
export type PostLinks201ResponseStatusEnum = typeof PostLinks201ResponseStatusEnum[keyof typeof PostLinks201ResponseStatusEnum];

/**
 * @export
 */
export const PostLinks201ResponseTypeEnum = {
    Onetime: 'onetime',
    Permanent: 'permanent'
} as const;
export type PostLinks201ResponseTypeEnum = typeof PostLinks201ResponseTypeEnum[keyof typeof PostLinks201ResponseTypeEnum];


/**
 * Check if a given object implements the PostLinks201Response interface.
 */
export function instanceOfPostLinks201Response(value: object): value is PostLinks201Response {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('expirationTime' in value) || value['expirationTime'] === undefined) return false;
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('toll' in value) || value['toll'] === undefined) return false;
    if (!('resource' in value) || value['resource'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function PostLinks201ResponseFromJSON(json: any): PostLinks201Response {
    return PostLinks201ResponseFromJSONTyped(json, false);
}

export function PostLinks201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLinks201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'url': json['url'],
        'ownerId': json['ownerId'],
        'alias': json['alias'],
        'name': json['name'],
        'description': json['description'],
        'status': json['status'],
        'type': json['type'],
        'expirationTime': json['expirationTime'],
        'deleted': json['deleted'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'toll': GetLinksByLinkUuidTollsActive200ResponseFromJSON(json['toll']),
        'resource': GetLinksByLinkUuidResourcesActive200ResponseFromJSON(json['resource']),
        'actions': ((json['actions'] as Array<any>).map(PostLinksByLinkUuidActions201ResponseFromJSON)),
    };
}

export function PostLinks201ResponseToJSON(json: any): PostLinks201Response {
    return PostLinks201ResponseToJSONTyped(json, false);
}

export function PostLinks201ResponseToJSONTyped(value?: PostLinks201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'url': value['url'],
        'ownerId': value['ownerId'],
        'alias': value['alias'],
        'name': value['name'],
        'description': value['description'],
        'status': value['status'],
        'type': value['type'],
        'expirationTime': value['expirationTime'],
        'deleted': value['deleted'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'toll': GetLinksByLinkUuidTollsActive200ResponseToJSON(value['toll']),
        'resource': GetLinksByLinkUuidResourcesActive200ResponseToJSON(value['resource']),
        'actions': ((value['actions'] as Array<any>).map(PostLinksByLinkUuidActions201ResponseToJSON)),
    };
}

