/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAccountTopupLinksRequest
 */
export interface PostAccountTopupLinksRequest {
    /**
     * 
     * @type {string}
     * @memberof PostAccountTopupLinksRequest
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof PostAccountTopupLinksRequest
     */
    assetNetwork: string;
    /**
     * 
     * @type {string}
     * @memberof PostAccountTopupLinksRequest
     */
    assetAddress: string;
    /**
     * 
     * @type {number}
     * @memberof PostAccountTopupLinksRequest
     */
    expiresIn?: number;
}

/**
 * Check if a given object implements the PostAccountTopupLinksRequest interface.
 */
export function instanceOfPostAccountTopupLinksRequest(value: object): value is PostAccountTopupLinksRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('assetNetwork' in value) || value['assetNetwork'] === undefined) return false;
    if (!('assetAddress' in value) || value['assetAddress'] === undefined) return false;
    return true;
}

export function PostAccountTopupLinksRequestFromJSON(json: any): PostAccountTopupLinksRequest {
    return PostAccountTopupLinksRequestFromJSONTyped(json, false);
}

export function PostAccountTopupLinksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAccountTopupLinksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'assetNetwork': json['assetNetwork'],
        'assetAddress': json['assetAddress'],
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
    };
}

export function PostAccountTopupLinksRequestToJSON(json: any): PostAccountTopupLinksRequest {
    return PostAccountTopupLinksRequestToJSONTyped(json, false);
}

export function PostAccountTopupLinksRequestToJSONTyped(value?: PostAccountTopupLinksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'assetNetwork': value['assetNetwork'],
        'assetAddress': value['assetAddress'],
        'expiresIn': value['expiresIn'],
    };
}

