/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAccountTopupLinks201Response
 */
export interface PostAccountTopupLinks201Response {
    /**
     * 
     * @type {string}
     * @memberof PostAccountTopupLinks201Response
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof PostAccountTopupLinks201Response
     */
    linkUuid: string;
    /**
     * 
     * @type {string}
     * @memberof PostAccountTopupLinks201Response
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof PostAccountTopupLinks201Response
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof PostAccountTopupLinks201Response
     */
    createdAt: string;
}

/**
 * Check if a given object implements the PostAccountTopupLinks201Response interface.
 */
export function instanceOfPostAccountTopupLinks201Response(value: object): value is PostAccountTopupLinks201Response {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('linkUuid' in value) || value['linkUuid'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PostAccountTopupLinks201ResponseFromJSON(json: any): PostAccountTopupLinks201Response {
    return PostAccountTopupLinks201ResponseFromJSONTyped(json, false);
}

export function PostAccountTopupLinks201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAccountTopupLinks201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'],
        'linkUuid': json['linkUuid'],
        'url': json['url'],
        'userId': json['userId'],
        'createdAt': json['createdAt'],
    };
}

export function PostAccountTopupLinks201ResponseToJSON(json: any): PostAccountTopupLinks201Response {
    return PostAccountTopupLinks201ResponseToJSONTyped(json, false);
}

export function PostAccountTopupLinks201ResponseToJSONTyped(value?: PostAccountTopupLinks201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'linkUuid': value['linkUuid'],
        'url': value['url'],
        'userId': value['userId'],
        'createdAt': value['createdAt'],
    };
}

