/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner } from './get-links-by-link-uuid-tolls-active200-response-toll-payment-requirements-inner';
import {
    GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerFromJSON,
    GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerFromJSONTyped,
    GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerToJSON,
    GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerToJSONTyped,
} from './get-links-by-link-uuid-tolls-active200-response-toll-payment-requirements-inner';

/**
 * 
 * @export
 * @interface PostLinksByLinkUuidTollsRequest
 */
export interface PostLinksByLinkUuidTollsRequest {
    /**
     * 
     * @type {Array<GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner>}
     * @memberof PostLinksByLinkUuidTollsRequest
     */
    tollPaymentRequirements: Array<GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInner>;
    /**
     * 
     * @type {number}
     * @memberof PostLinksByLinkUuidTollsRequest
     */
    paymentValidityPeriodSeconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PostLinksByLinkUuidTollsRequest
     */
    paymentValidityQueryCount?: number | null;
}

/**
 * Check if a given object implements the PostLinksByLinkUuidTollsRequest interface.
 */
export function instanceOfPostLinksByLinkUuidTollsRequest(value: object): value is PostLinksByLinkUuidTollsRequest {
    if (!('tollPaymentRequirements' in value) || value['tollPaymentRequirements'] === undefined) return false;
    return true;
}

export function PostLinksByLinkUuidTollsRequestFromJSON(json: any): PostLinksByLinkUuidTollsRequest {
    return PostLinksByLinkUuidTollsRequestFromJSONTyped(json, false);
}

export function PostLinksByLinkUuidTollsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLinksByLinkUuidTollsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tollPaymentRequirements': ((json['tollPaymentRequirements'] as Array<any>).map(GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerFromJSON)),
        'paymentValidityPeriodSeconds': json['paymentValidityPeriodSeconds'] == null ? undefined : json['paymentValidityPeriodSeconds'],
        'paymentValidityQueryCount': json['paymentValidityQueryCount'] == null ? undefined : json['paymentValidityQueryCount'],
    };
}

export function PostLinksByLinkUuidTollsRequestToJSON(json: any): PostLinksByLinkUuidTollsRequest {
    return PostLinksByLinkUuidTollsRequestToJSONTyped(json, false);
}

export function PostLinksByLinkUuidTollsRequestToJSONTyped(value?: PostLinksByLinkUuidTollsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tollPaymentRequirements': ((value['tollPaymentRequirements'] as Array<any>).map(GetLinksByLinkUuidTollsActive200ResponseTollPaymentRequirementsInnerToJSON)),
        'paymentValidityPeriodSeconds': value['paymentValidityPeriodSeconds'],
        'paymentValidityQueryCount': value['paymentValidityQueryCount'],
    };
}

