/* tslint:disable */
/* eslint-disable */
/**
 * Gatepay API
 * API documentation for Gatepay
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutLinksByUuidRequest
 */
export interface PutLinksByUuidRequest {
    /**
     * 
     * @type {string}
     * @memberof PutLinksByUuidRequest
     */
    status?: PutLinksByUuidRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PutLinksByUuidRequest
     */
    alias?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutLinksByUuidRequest
     */
    type?: PutLinksByUuidRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PutLinksByUuidRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutLinksByUuidRequest
     */
    description?: string | null;
}


/**
 * @export
 */
export const PutLinksByUuidRequestStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Used: 'used',
    Expired: 'expired'
} as const;
export type PutLinksByUuidRequestStatusEnum = typeof PutLinksByUuidRequestStatusEnum[keyof typeof PutLinksByUuidRequestStatusEnum];

/**
 * @export
 */
export const PutLinksByUuidRequestTypeEnum = {
    Onetime: 'onetime',
    Permanent: 'permanent'
} as const;
export type PutLinksByUuidRequestTypeEnum = typeof PutLinksByUuidRequestTypeEnum[keyof typeof PutLinksByUuidRequestTypeEnum];


/**
 * Check if a given object implements the PutLinksByUuidRequest interface.
 */
export function instanceOfPutLinksByUuidRequest(value: object): value is PutLinksByUuidRequest {
    return true;
}

export function PutLinksByUuidRequestFromJSON(json: any): PutLinksByUuidRequest {
    return PutLinksByUuidRequestFromJSONTyped(json, false);
}

export function PutLinksByUuidRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutLinksByUuidRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function PutLinksByUuidRequestToJSON(json: any): PutLinksByUuidRequest {
    return PutLinksByUuidRequestToJSONTyped(json, false);
}

export function PutLinksByUuidRequestToJSONTyped(value?: PutLinksByUuidRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'alias': value['alias'],
        'type': value['type'],
        'name': value['name'],
        'description': value['description'],
    };
}

